export const hostname = "http://localhost:3000";

// export const blogType = ["ALL", ] 

export enum GenreEnum {
  ACTION = "ACTION",
  ADVENTURE = "ADVENTURE",
  ROMANCE = "ROMANCE",
  SHOUJO = "SHOUJO",
  COMEDY = "COMEDY",
  DRAMA = "DRAMA",
  FANTASY = "FANTASY",
  HORROR = "HORROR",
  MAGIC = "MAGIC",
  MECHA = "MECHA",
  MYSTERY = "MYSTERY",
  SCI_FI = "SCI_FI",
  SUPERNATURAL = "SUPERNATURAL",
  THRILLER = "THRILLER",
  SPORTS = "SPORTS",
  PSYCHOLOGICAL = "PSYCHOLOGICAL",
  HISTORICAL = "HISTORICAL",
  MILITARY = "MILITARY",
  MUSIC = "MUSIC",
  SLICE_OF_LIFE = "SLICE_OF_LIFE",
  HAREM = "HAREM",
  ISEKAI = "ISEKAI",
  SEINEN = "SEINEN",
  SHOUNEN = "SHOUNEN",
  JOSEI = "JOSEI",
  ECCHI = "ECCHI",
  HENTAI = "HENTAI",
  MAGICAL_GIRL = "MAGICAL_GIRL",
  VAMPIRE = "VAMPIRE",
  ZOMBIE = "ZOMBIE",
}

export const Genres = [
  GenreEnum.ACTION,
  GenreEnum.ADVENTURE,
  GenreEnum.ROMANCE,
  GenreEnum.SHOUJO,
  GenreEnum.COMEDY,
  GenreEnum.DRAMA,
  GenreEnum.FANTASY,
  GenreEnum.HORROR,
  GenreEnum.MAGIC,
  GenreEnum.MECHA,
  GenreEnum.MYSTERY,
  GenreEnum.SCI_FI,
  GenreEnum.SUPERNATURAL,
  GenreEnum.THRILLER,
  GenreEnum.SPORTS,
  GenreEnum.PSYCHOLOGICAL,
  GenreEnum.HISTORICAL,
  GenreEnum.MILITARY,
  GenreEnum.MUSIC,
  GenreEnum.SLICE_OF_LIFE,
  GenreEnum.HAREM,
  GenreEnum.ISEKAI,
  GenreEnum.SEINEN,
  GenreEnum.SHOUNEN,
  GenreEnum.JOSEI,
  GenreEnum.ECCHI,
  GenreEnum.HENTAI,
  GenreEnum.MAGICAL_GIRL,
  GenreEnum.VAMPIRE,
  GenreEnum.ZOMBIE,
];
