export const hostname = "http://localhost:3000";

export enum GenreEnum {
  ACTION = "ACTION",
  ADVENTURE = "ADVENTURE",
  ROMANCE = "ROMANCE",
  COMEDY = "COMEDY",
  SHOUNEN = "SHOUNEN",
  SEINEN = "SEINEN",
  DRAMA = "DRAMA",
  FANTASY = "FANTASY",
  SHOUJO = "SHOUJO",
  ISEKAI = "ISEKAI",
  SPORTS = "SPORTS",
  SUPERNATURAL = "SUPERNATURAL",
  SLICE_OF_LIFE = "SLICE_OF_LIFE",
  ECCHI = "ECCHI",
  HAREM = "HAREM",
  HENTAI = "HENTAI",
  MAGIC = "MAGIC",
  HORROR = "HORROR",
  MYSTERY = "MYSTERY",
  THRILLER = "THRILLER",
  MUSIC = "MUSIC",
  PSYCHOLOGICAL = "PSYCHOLOGICAL",
  CRIME = "CRIME",
  ZOMBIE = "ZOMBIE",
  SCI_FI = "SCI_FI",
  MECHA = "MECHA",
  HISTORICAL = "HISTORICAL",
  MILITARY = "MILITARY",
  JOSEI = "JOSEI",
  MAGICAL_GIRL = "MAGICAL_GIRL",
  VAMPIRE = "VAMPIRE",
}

export const Genres = [
  GenreEnum.ACTION,
  GenreEnum.ADVENTURE,
  GenreEnum.ROMANCE,
  GenreEnum.COMEDY,
  GenreEnum.SHOUNEN,
  GenreEnum.SEINEN,
  GenreEnum.DRAMA,
  GenreEnum.FANTASY,
  GenreEnum.SHOUJO,
  GenreEnum.ISEKAI,
  GenreEnum.SPORTS,
  GenreEnum.SUPERNATURAL,
  GenreEnum.SLICE_OF_LIFE,
  GenreEnum.ECCHI,
  GenreEnum.HAREM,
  GenreEnum.HENTAI,
  GenreEnum.MAGIC,
  GenreEnum.HORROR,
  GenreEnum.MYSTERY,
  GenreEnum.THRILLER,
  GenreEnum.MUSIC,
  GenreEnum.PSYCHOLOGICAL,
  GenreEnum.CRIME,
  GenreEnum.ZOMBIE,
  GenreEnum.SCI_FI,
  GenreEnum.MECHA,
  GenreEnum.HISTORICAL,
  GenreEnum.MILITARY,
  GenreEnum.JOSEI,
  GenreEnum.MAGICAL_GIRL,
  GenreEnum.VAMPIRE,
];
